# version: '3'

services:
  rabbit:
    container_name: nameko-example-rabbitmq
    image: rabbitmq:3.7-management
    ports:
      - "15673:15672" # Exposing RabbitMQ web management on different port for convenience
    restart: always

  mysql:
    container_name: nameko-example-mysql
    image: mysql:5.7
    ports:
      - "3307:3306" # Exposing MySQL on different port for convenience
    environment:
      MYSQL_DATABASE: "soa_payment_notif"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
     - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  gateway:
    build: ./gateway
    container_name: nameko-example-gateway
    depends_on:
      - rabbit
    ports:
      - "8009:8000"
    links:
      - "rabbit:nameko-example-rabbitmq"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"
